#+TAGS: bread candy
#+TAGS: breakfast desert
#+TAGS: american turkish

* English Muffins 				   :bread:breakfast:american:
  :PROPERTIES:
  :Source:   Good Eats - S14E03
  :Title:    English Muffins  
  :Ingredients: :flour:sugar:salt:powdered milk:shortening:yeast: 
  :Format:   0
  :END:
** Ingredients
   + 12oz flour
   + 1/4 oz active dry yeast
   + 1 tbs sugar
   + 1 tsp salt
   + 1.5 oz powdered milk  
   + 10 oz Water
   + 1 tbs shortening

** Directions
   1. Mix dry ingreadants 10 secs. 
   2. heat water and shortening to 120 - 130 degrees (1 - 2 min microwave)
   3. Add water & shortening and slowly bring mixter to medium,  mix 3 minutes (scrape as needed)
   4. Refrigerate over night
   5. Mix again for another 3 minutes
   6. Dose out batter into 8 circular rings on greased pan/ring.
   7. Cover with parchment paper and Let rest 60 minutes
   8. Place another sheet pan ontop and bake in the middle of 400 degree oven 20 - 30 minutes or until 210 degrees
   9. 5 minutes before cooking is complete,  remove parchment paper and upper sheet pan to brown tops
   10. Cool 10 minutes before removing from molds

  
** Notes
   + Substituting 1tbs Butter for shortening produces acceptable results

* Turkish Delight				       :candy:desert:turkish:
  :PROPERTIES:
  :Source:   http://www.ranum.com/fun/recipes/turkishdelight.html
  :Title:    Turkish Delight
  :Ingredients: :sugar:lemon juice:cornstarch:cream of tartar:rose water:
  :Format:   0
  :END:
  
** Ingredients
   + 4 cups sugar
   + 4 1/2 cups water
   + Juice of one fresh lemon or lime
   + 1 cup cornstarch
   + 1 tsp cream of tartar
   + up to 2 tablespoons flavoring
     
** Directrions
   1. Grease one 9x9 inch silicone pan
   2. Juice the lemon, then mix the lemon, the 4 cups of sugar, and 1 ½ cups of water in a saucepan. 
   3. Turn on the heat and put the candy thermometer in.  stir it occasionally until it reaches 230F then turn off heat
   4. While the sugar is boiling  put the 1 cup of cornstarch and 3 cups of water in the other saucepan. Add the cream of tartar. Stir gently.
   5. Once cornstarch mixture is completely incorporated turn on medium heat and stir until just bearly thickened.
   6. Goal is to have sugar come up to temperature roughly the same time cornstarch thickens. 
   7. Mix bearly thickened cornstarch into sugar syrup and bring to a boil.  Stir periodically.
   8. Cook until small spoonful of mixture plunged into icewater results in ball of sugar that sticks to thumb but not index finger when pressed together.
   9. When cooked,  turn off heat,  mix in flavoring and turn out into 9x9 silicone pan
   10. Rest over night
   11. Turn out onto cutting board covered in mixture of 1/2 cornstarch 1/2 powdered sugar,  cut,  toss in mixture, store between sheets of wax paper

** Notes
*** Example Flavors
    + Rose Water
      - 1 tablespoon rose water
      - 1 tablespoon pomegranate juice (mostly for coloring), can use grenadine
    + Lemon & Clove
      - 1 tablespoon lemon extract
      - 1 tablespoon clove-water tea (take a dozen cloves and boil them in ½ cup of water until there is 1 tablespoon of liquid left. Drain. Use.)
    + Mango
      - 1 tablespoon mango extract   
*** Cornstarch mixture
    + This is the trickiest part of the whole process. Once the sugar hits 230 degrees F, turn it off, and turn your attention to the corn starch/water mix. Turn on medium heat and stir it constantly while you bring it up to a simmer. When the cornstarch starts to boil it will very quickly convert into a thick paste. You need to catch it right before it does that; pay attention to nothing else and stir the cornstarch while it heats. As soon as you feel it starting to get a bit sticky/thick on the bottom of the pan, lift up your spatula or spoon and if there’s goopy-looking gluey stuff on the bottom, you’re just about ready to take it off the heat. I usually turn the heat off and stir a bit more and suddenly it’ll begin to thicken into a creamy glue. Do not let it overdevelop – as soon as it turns creamy, pour it into the sugar syrup and stir it in. If it turns into hard rubbery stuff your best bet is to dump it and make another batch of cornstarch really quickly.

*** Cutting Finished Candy
    + Get a flat-bladed knife like a cleaver or the insanely expensive sushi knife shown above, and powder its edges, then quickly press it through the turkish delight to cut it into strips. Cut fast with a pressure downward; don’t try to draw-cut or it’ll curl and stick to itself. Put the cut strips into the powder container so that the exposed fresh edges get powdered. Then line them up on the cutting board again and cross-cut them.
*** Storage
    + Do not ever put turkish delight in an airtight container. It’ll release moisture and get sticky. My favorite way of storing it is in a little paper bag that I can shake periodically.

